### ISSUE TITLE
How can `Binding` vars be used?

### ISSUE THREAD

**Issue by lawmaestro** [adam-zethraeus/Republished#1]
Hey, thanks for contributing this library! It's helped partly solve a problem I faced when having nested Input/Output objects within my view model (mostly for the sakes of nice namespacing). For example:

````
final class ViewModel: ObservableObject {
  var input: Input
  @Republished var output: Output
  
  class Output: ObservableObject {
    @Published var test: Bool
  }
}

struct ContentView: View {
  @ObservedObject var viewModel: ViewModel
}
````

However, one problem I have faced is if I have a `@Published` var within an `ObservableObject` (in the above example `test`) and that object is held as a `@Republished` var, then I'm no longer able to inject that into a view  and make a `@Binding` var from it as it throws a `get-only` compile error. This was previously possible when using a `@Published` property wrapper.

Is there any way around this? Happy to elaborate on this if what I'm trying to explain isn't clear.

Thanks!

**Comment by adam-zethraeus** [comment]
Hey! I just saw this, sorry! I'll take a look. (But if you ever did solve it, please PR :) )

**Comment by adam-zethraeus** [comment]
(Quick look only: Might just be that `private let republished: Republishing` would need to be `var` to have the mutable behavior you're looking for.)

**Comment by adam-zethraeus** [comment]
@lawmaestro would this suit your use case? https://github.com/adam-zethraeus/Republished/pull/2

(will merge eventually in any case, but would love to know!)

**Comment by lawmaestro** [comment]
@adam-zethraeus this looks great - thanks! On the face of it, I think it should fulfil this use-case. I'll test out the change shortly and confirm back.

**Comment by adam-zethraeus** [comment]
fun! let me know how it feels!

**Comment by lawmaestro** [comment]
Hey @adam-zethraeus I've just checked out the latest version with your change and this does indeed address the issue - nice one! 🙌
